"""more questions

Revision ID: 06e37f6b8d95
Revises: 528a6cb191f6
Create Date: 2019-03-26 23:52:29.228362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e37f6b8d95'
down_revision = '528a6cb191f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('q10', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q11', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q12', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q13', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q14', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q15', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q16', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q17', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q18', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q19', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q20', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q21', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q22', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q23', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q24', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q25', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q26', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q27', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q28', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q29', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q3', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q30', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q4', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q5', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q6', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q7', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q8', sa.String(length=64), nullable=True))
    op.add_column('response', sa.Column('q9', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', 'q9')
    op.drop_column('response', 'q8')
    op.drop_column('response', 'q7')
    op.drop_column('response', 'q6')
    op.drop_column('response', 'q5')
    op.drop_column('response', 'q4')
    op.drop_column('response', 'q30')
    op.drop_column('response', 'q3')
    op.drop_column('response', 'q29')
    op.drop_column('response', 'q28')
    op.drop_column('response', 'q27')
    op.drop_column('response', 'q26')
    op.drop_column('response', 'q25')
    op.drop_column('response', 'q24')
    op.drop_column('response', 'q23')
    op.drop_column('response', 'q22')
    op.drop_column('response', 'q21')
    op.drop_column('response', 'q20')
    op.drop_column('response', 'q19')
    op.drop_column('response', 'q18')
    op.drop_column('response', 'q17')
    op.drop_column('response', 'q16')
    op.drop_column('response', 'q15')
    op.drop_column('response', 'q14')
    op.drop_column('response', 'q13')
    op.drop_column('response', 'q12')
    op.drop_column('response', 'q11')
    op.drop_column('response', 'q10')
    # ### end Alembic commands ###
