"""score

Revision ID: 0e77f1d5ec80
Revises: e4595fc189ea
Create Date: 2019-03-28 19:59:29.022448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e77f1d5ec80'
down_revision = 'e4595fc189ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', 'score')
    # ### end Alembic commands ###
