"""add timestamp

Revision ID: 96d83237dd53
Revises: 58a9b577781f
Create Date: 2019-03-25 23:41:01.848391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d83237dd53'
down_revision = '58a9b577781f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_response_timestamp'), 'response', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_timestamp'), table_name='response')
    op.drop_column('response', 'timestamp')
    # ### end Alembic commands ###
