"""add rank

Revision ID: d9f7173a13fb
Revises: 0e77f1d5ec80
Create Date: 2019-03-28 20:36:42.380943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f7173a13fb'
down_revision = '0e77f1d5ec80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('rank', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', 'rank')
    # ### end Alembic commands ###
